sudo: required

language: ruby

env:
  - RACK_ENV=test
  - SH=bash
  - PACKAGE_VERSION="1.0"

before_install:
  - gem install prawn -v 2.1.0   # dependance d'asciidoctor
  - gem install asciidoctor      # pour générer votre HTML
  - gem install asciidoctor-pdf --pre # pour générer le PDF

jobs:
  include:
    - stage: build
      name: "Compilation"
      script: 
        - gcc main.c -o main
    - stage: test
      name: "Unit Tests"
      script: 
        - ./main
    - stage: deploy
      name: "Deploy to HTML & PDF"
      script:
        - mkdir public
        - asciidoctor README.adoc -o public/index.html
        - asciidoctor-pdf README.adoc -o public/manuel.pdf
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  committer-from-gh: true
  local-dir: gh-pages
  on:
    branch: main