// View this document online at https://asciidoctor.org/docs/asciidoc-writers-guide/
= AsciiDoc Writer's Guide
Dan Allen <https://github.com/mojavelinux[@mojavelinux]>; Sarah White <https://github.com/graphitefriction[@graphitefriction]>
:description: This guide describes the basic structure of an AsciiDoc document, how to create your first AsciiDoc document, how to add other structural elements such as lists, block quotes and source code, and how to convert an AsciiDoc document to HTML, DocBook and PDF.
:keywords: AsciiDoc, Asciidoctor, syntax, reference, learn, how to, writers, authors
:page-description: {description}
:page-keywords: {keywords}
:page-layout: docs
ifndef::env-site[]
:toc: left
:icons: font
:idprefix:
:idseparator: -
:sectanchors:
:source-highlighter: highlightjs
endif::[]
:experimental:
:mdash: &#8212;
:language: asciidoc
:source-language: {language}
:table-caption!:
:example-caption!:
:figure-caption!:
:imagesdir: ../images
:includedir: _includes
// Refs
:asciidoc-dl-ref: https://sourceforge.net/projects/asciidoc/files/latest/download
:asciidoc-editor-ref: http://asciidoc.org/#_editor_support
:asciidoc-faq-ref: http://asciidoc.org/faq.html
:asciidoc-guide-ref: http://asciidoc.org/userguide.html
:asciidoc-install-ref: http://asciidoc.org/INSTALL.html
:asciidoc-list-ref: https://groups.google.com/group/asciidoc
:asciidoctor-ref: https://asciidoctor.org/
:asciidoctor-gem-ref: https://rubygems.org/gems/asciidoctor
:uri-install: https://asciidoctor.org/docs/install-toolchain/
:fopub-doc-ref: https://github.com/asciidoctor/asciidoctor-fopub/blob/master/README.adoc
:user-ref: https://asciidoctor.org/docs/user-manual
:docs-ref: https://asciidoctor.org/docs
:uri-editing: https://asciidoctor.org/docs/editing-asciidoc-with-live-preview/
:gist-ref: https://gist.github.com
:publican-ref: https://fedorahosted.org/publican
:uri-quick: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/
:uri-what-asciidoc: https://asciidoctor.org/docs/what-is-asciidoc-why-use-it

////
Raw material about block masquerading:

Adding [listing] above the block will fix this.
A [listing] over a delimited block with four dots is indistinguishable from a delimited block with four hyphens.
I refer to this as block masquerading, since many of the blocks can masquerade as other blocks using a style to "force" the block type.
The most common form of this is the open block, which is two hyphens.
An open block can accept any "style" (i.e., block type) and become that block.
To give you an example, here's an open block acting as a quote block:

```
[quote]
--
A famous quote.
--
```

Likewise, a literal block acting as a listing block:

```
[listing]
....
puts "Hello, World!"
....
````

Note that "listing" and "source" are effectively the same, except that source triggers the source filter whereas listing does not.
////

////
TODO:

- show sample output
- literal paragraphs
- footnotes (in section on admonitions)
- clarification about doctypes and level-0 sections (perhaps in an admonition block)
- fill out the "Why AsciiDoc works" section
- move "Who's using AsciiDoc?" to one of the opening sections, mention some examples
- include bit about importance of documentation, profound impact on project, greatest project/initiative in the world, but if nobody knows about it...

- consult https://gist.github.com/mojavelinux/4761050 for ideas to integrate
- brief bit comparing AsciiDoc to Markdown
- mention the required quoting of block attributes when using AsciiDoc
////

This guide provides a gentle introduction to AsciiDoc, a _plain text_ documentation *syntax* and *processor*.
This introduction is intended for anyone who wants to reduce the effort required to write and publish content, whether for technical documentation, articles, web pages or good ol'-fashioned prose.

TIP: If you want to know what AsciiDoc is all about, find the answer in {uri-what-asciidoc}[What is AsciiDoc?].
If you're looking for a concise survey of the AsciiDoc syntax, consult the {uri-quick}[AsciiDoc Syntax Quick Reference].

In this guide, you'll learn:

- The basic structure of an AsciiDoc document
- How to create your first AsciiDoc document
- How to add other structural elements such as lists, block quotes and source code
- How to convert an AsciiDoc document to HTML, DocBook and PDF

In addition to covering the AsciiDoc basics, this guide also suggests a set of conventions to help you create more consistent documents and maximize your writing productivity.

Let's dive in to AsciiDoc!

== Writing in AsciiDoc

The goal of this section is to teach you how to compose your first AsciiDoc document.
Hopefully, when you look back, you'll agree it just makes sense.

Your adventure with AsciiDoc begins in your favorite text editor.

=== It's just text, mate.

Since AsciiDoc syntax is just _plain text_, you can write an AsciiDoc document using _any_ text editor.
You don't need complex word processing programs like Microsoft Word, OpenOffice Writer or Google Docs.
In fact, you _shouldn't_ use these programs because they add cruft to your document (that you can't see) and makes conversion tedious.

TIP: While it's true any text editor will do, I recommend selecting an editor that supports syntax highlighting for AsciiDoc.
The *[red]##c##[green]##o##[purple]##l##[fuchsia]##o##[blue]##r##* brings contrast to the text, making it easier to read.
The highlighting also confirms when you've entered the correct syntax for an inline or block element.

The most popular application for editing plain text on macOS is *TextMate*.
A similar choice on Linux is *GEdit*.
On Windows, stay away from Notepad and Wordpad because they produce plain text which is not cross-platform friendly.
Opt instead for a competent text editor like *Notepad++*.
If you're a programmer (or a writer with an inner geek), you'll likely prefer *Vim*, *Emacs*, or *Sublime Text*, all of which are available cross-platform.
The key feature all these editors share is syntax highlighting for AsciiDoc.

TIP: Previewing the output of the document while editing can be helpful.
To learn how to setup instant preview, check out the {uri-editing}[Editing AsciiDoc with Live Preview] tutorial.

Open up your favorite text editor and get ready to write some AsciiDoc!

=== Content is king!

include::{includedir}/para.adoc[]

Just like that, *you're writing in AsciiDoc!*
As you can see, it's just like writing an e-mail.

Save the file with a file extension of `.adoc`.

TIP: If you want to find out how to convert the document to HTML, DocBook or PDF, skip ahead to the section on <<converting-your-document>>.

// Update convert section with new link to guide

==== Wrapped text and hard line breaks

include::{includedir}/para-line-break.adoc[]

=== Admonitions

include::{includedir}/admonition.adoc[tag=intro]

include::{includedir}/admonition.adoc[tag=icon]

An admonition paragraph is rendered in a callout box with the admonition label--or its corresponding icon--in the gutter.
Icons are enabled by setting the `icons` attribute on the document.

// Should icon settings be specified here, in a more detailed section further down, or do we need a styling document?

NOTE: Admonitions can also encapsulate any block content, which we'll cover later.

All words and no emphasis makes the document monotonous.
Let's give our paragraphs some [big]*_emotion_*.

=== Mild punctuation, strong impact

Just as we emphasize certain words and phrases when we speak, we can emphasize them in text by surrounding them with punctuation.
AsciiDoc refers to this markup as _quoted text_.

==== Quoted text

For instance, in an e-mail, you might "`speak`" a word louder by enclosing it in asterisks.

[source]
I can't believe it, we *won*!

As you would expect, the asterisks make the text *won* bold.
You can almost sense the emotion.
This is one example of quoted (i.e., formatted) text.

NOTE: The term "`quote`" is used liberally here to apply to any symbols that surround text in order to apply emphasis or special meaning.

Here are the forms of quoted text that AsciiDoc recognizes:

.Bold, italic, and monospace formatting syntax
[source]
----
include::{includedir}/ex-text.adoc[tag=b-bold-italic-mono]
----

When you want to quote text (e.g., place emphasis) somewhere other than at the boundaries of a word, you need to double up the punctuation.

.Result: Bold, italic, and monospace text
====
include::{includedir}/ex-text.adoc[tag=b-bold-italic-mono]
====

Any quoted text can be prefixed with an attribute list.
The first positional attribute is treated as a role.
The role can be used to apply custom styling to the text.
For instance:

[source]
Type the word [.userinput]#asciidoc# into the search bar.

When converting to HTML, the word "`asciidoc`" is wrapped in `<span>` tags and the role is used as the element's CSS class:

[source,xml]
<span class="userinput">asciidoc</span>

You can apply styles to the text using CSS.

You may not always want these substitutions to take place.
In those cases, you'll need to use markup to escape the text.

==== Preventing substitution

If you are getting quoted text behavior where you don't want it, you can use a backslash or a passthrough macro to prevent it.

include::{includedir}/subs-prevent.adoc[tag=backslash]

include::{includedir}/pass-macro.adoc[]

.Single plus enclosure

To exclude a phrase from substitutions, enclose it in plus signs (`+`).

[source]
----
This +*literal*+ will appear as *literal*.
----
